version: "3"

services:
  app:
    build: .
    image: clubecuritibano/golfe-api:app
    command: npm start
    container_name: Golfe-API
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    command: npm run start:dev
    env_file:
      - .env